export const CANVAS = {
  WIDTH: 1024,
  HEIGHT: 768,
  BACKGROUND_COLOR: 0xfff8f0,
} as const;

export const TIMING = {
  HINT_LEVEL_1_DELAY_MS: 5000,
  HINT_LEVEL_2_DELAY_MS: 10000,
  HINT_LEVEL_3_DELAY_MS: 15000,
  SUCCESS_PAUSE_MS: 1500,
  SESSION_MAX_DURATION_SEC: 600,
  SESSION_WIND_DOWN_SEC: 480,
  ACCURACY_WINDOW: 10,
  MASTERY_THRESHOLD: 3,
  MASTERY_MIN_SESSIONS: 2,
} as const;

export const SPRITE = {
  CELL_WIDTH: 250,
  CELL_HEIGHT: 250,
  DISPLAY_SCALE: 0.38,
  COLUMNS: 8,
  ROWS: 8,
} as const;

export const INTERACTION = {
  DRAG_OVERLAP_THRESHOLD: 0.3,
  TAP_DISTRACTOR_COUNT: 4,
  DRAG_DISTRACTOR_COUNT: 2,
} as const;
